//
// File generated by HDevelop for HALCON/.NET (C#) Version 20.11.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public  class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

  // Procedures 
  // Chapter: Graphics / Text
  // Short Description: This procedure writes one or multiple text messages. 
  public static void disp_message (HTuple hv_WindowHandle, HTuple hv_String, HTuple hv_CoordSystem, 
      HTuple hv_Row, HTuple hv_Column, HTuple hv_Color, HTuple hv_Box)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_GenParamName = new HTuple(), hv_GenParamValue = new HTuple();
    HTuple   hv_Color_COPY_INP_TMP = new HTuple(hv_Color);
    HTuple   hv_Column_COPY_INP_TMP = new HTuple(hv_Column);
    HTuple   hv_CoordSystem_COPY_INP_TMP = new HTuple(hv_CoordSystem);
    HTuple   hv_Row_COPY_INP_TMP = new HTuple(hv_Row);

    // Initialize local and output iconic variables 
    //This procedure displays text in a graphics window.
    //
    //Input parameters:
    //WindowHandle: The WindowHandle of the graphics window, where
    //   the message should be displayed.
    //String: A tuple of strings containing the text messages to be displayed.
    //CoordSystem: If set to 'window', the text position is given
    //   with respect to the window coordinate system.
    //   If set to 'image', image coordinates are used.
    //   (This may be useful in zoomed images.)
    //Row: The row coordinate of the desired text position.
    //   You can pass a single value or a tuple of values.
    //   See the explanation below.
    //   Default: 12.
    //Column: The column coordinate of the desired text position.
    //   You can pass a single value or a tuple of values.
    //   See the explanation below.
    //   Default: 12.
    //Color: defines the color of the text as string.
    //   If set to [] or '' the currently set color is used.
    //   If a tuple of strings is passed, the colors are used cyclically
    //   for every text position defined by Row and Column,
    //   or every new text line in case of |Row| == |Column| == 1.
    //Box: A tuple controlling a possible box surrounding the text.
    //   Its entries:
    //   - Box[0]: Controls the box and its color. Possible values:
    //     -- 'true' (Default): An orange box is displayed.
    //     -- 'false': No box is displayed.
    //     -- color string: A box is displayed in the given color, e.g., 'white', '#FF00CC'.
    //   - Box[1] (Optional): Controls the shadow of the box. Possible values:
    //     -- 'true' (Default): A shadow is displayed in
    //               darker orange if Box[0] is not a color and in 'white' otherwise.
    //     -- 'false': No shadow is displayed.
    //     -- color string: A shadow is displayed in the given color, e.g., 'white', '#FF00CC'.
    //
    //It is possible to display multiple text strings in a single call.
    //In this case, some restrictions apply on the
    //parameters String, Row, and Column:
    //They can only have either 1 entry or n entries.
    //Behavior in the different cases:
    //   - Multiple text positions are specified, i.e.,
    //       - |Row| == n, |Column| == n
    //       - |Row| == n, |Column| == 1
    //       - |Row| == 1, |Column| == n
    //     In this case we distinguish:
    //       - |String| == n: Each element of String is displayed
    //                        at the corresponding position.
    //       - |String| == 1: String is displayed n times
    //                        at the corresponding positions.
    //   - Exactly one text position is specified,
    //      i.e., |Row| == |Column| == 1:
    //      Each element of String is display in a new textline.
    //
    //
    //Convert the parameters for disp_text.
    if ((int)((new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(new HTuple()))).TupleOr(
        new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(new HTuple())))) != 0)
    {

      hv_Color_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();

      return;
    }
    if ((int)(new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(-1))) != 0)
    {
      hv_Row_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP = 12;
    }
    if ((int)(new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(-1))) != 0)
    {
      hv_Column_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP = 12;
    }
    //
    //Convert the parameter Box to generic parameters.
    hv_GenParamName.Dispose();
    hv_GenParamName = new HTuple();
    hv_GenParamValue.Dispose();
    hv_GenParamValue = new HTuple();
    if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(0))) != 0)
    {
      if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleEqual("false"))) != 0)
      {
        //Display no box
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
            "box");
        hv_GenParamName.Dispose();
        hv_GenParamName = ExpTmpLocalVar_GenParamName;
        }
        }
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
            "false");
        hv_GenParamValue.Dispose();
        hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
        }
        }
      }
      else if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleNotEqual("true"))) != 0)
      {
        //Set a color other than the default.
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
            "box_color");
        hv_GenParamName.Dispose();
        hv_GenParamName = ExpTmpLocalVar_GenParamName;
        }
        }
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
            hv_Box.TupleSelect(0));
        hv_GenParamValue.Dispose();
        hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
        }
        }
      }
    }
    if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(1))) != 0)
    {
      if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleEqual("false"))) != 0)
      {
        //Display no shadow.
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
            "shadow");
        hv_GenParamName.Dispose();
        hv_GenParamName = ExpTmpLocalVar_GenParamName;
        }
        }
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
            "false");
        hv_GenParamValue.Dispose();
        hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
        }
        }
      }
      else if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleNotEqual("true"))) != 0)
      {
        //Set a shadow color other than the default.
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
            "shadow_color");
        hv_GenParamName.Dispose();
        hv_GenParamName = ExpTmpLocalVar_GenParamName;
        }
        }
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
            hv_Box.TupleSelect(1));
        hv_GenParamValue.Dispose();
        hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
        }
        }
      }
    }
    //Restore default CoordSystem behavior.
    if ((int)(new HTuple(hv_CoordSystem_COPY_INP_TMP.TupleNotEqual("window"))) != 0)
    {
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP = "image";
    }
    //
    if ((int)(new HTuple(hv_Color_COPY_INP_TMP.TupleEqual(""))) != 0)
    {
      //disp_text does not accept an empty string for Color.
      hv_Color_COPY_INP_TMP.Dispose();
      hv_Color_COPY_INP_TMP = new HTuple();
    }
    //
    HOperatorSet.DispText(hv_WindowHandle, hv_String, hv_CoordSystem_COPY_INP_TMP, 
        hv_Row_COPY_INP_TMP, hv_Column_COPY_INP_TMP, hv_Color_COPY_INP_TMP, hv_GenParamName, 
        hv_GenParamValue);

    hv_Color_COPY_INP_TMP.Dispose();
    hv_Column_COPY_INP_TMP.Dispose();
    hv_CoordSystem_COPY_INP_TMP.Dispose();
    hv_Row_COPY_INP_TMP.Dispose();
    hv_GenParamName.Dispose();
    hv_GenParamValue.Dispose();

    return;
  }

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_Image, ho_Rectangle1, ho_Contours;
    HObject ho_ImageReduced, ho_RegionFillUp, ho_RegionOpening;
    HObject ho_ConnectedRegions, ho_SelectedRegions, ho_ReducedImage;
    HObject ho_Region1, ho_ConnectedRegions1, ho_Rectangle=null;

    // Local control variables 

    HTuple hv_WindowHandle1 = new HTuple(), hv_Row1 = new HTuple();
    HTuple hv_Column1 = new HTuple(), hv_Row2 = new HTuple();
    HTuple hv_Column2 = new HTuple(), hv_Number = new HTuple();
    HTuple hv_Area = new HTuple(), hv_Row = new HTuple(), hv_Column = new HTuple();
    HTuple hv_Index = new HTuple(), hv_WindowHandle = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_Rectangle1);
    HOperatorSet.GenEmptyObj(out ho_Contours);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_RegionFillUp);
    HOperatorSet.GenEmptyObj(out ho_RegionOpening);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_ReducedImage);
    HOperatorSet.GenEmptyObj(out ho_Region1);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions1);
    HOperatorSet.GenEmptyObj(out ho_Rectangle);
    //121
    HOperatorSet.SetWindowAttr("background_color","black");
    HOperatorSet.OpenWindow(0,0,512,512,0,"visible","",out hv_WindowHandle1);
    HDevWindowStack.Push(hv_WindowHandle1);
    ho_Image.Dispose();
    HOperatorSet.ReadImage(out ho_Image, "C:/Users/Administrator/Desktop/标定/算法测试题/230109_作业图片/7_3.tif.tif");
    hv_Row1.Dispose();hv_Column1.Dispose();hv_Row2.Dispose();hv_Column2.Dispose();
    HOperatorSet.DrawRectangle1(hv_WindowHandle1, out hv_Row1, out hv_Column1, out hv_Row2, 
        out hv_Column2);
    ho_Rectangle1.Dispose();
    HOperatorSet.GenRectangle1(out ho_Rectangle1, hv_Row1, hv_Column1, hv_Row2, hv_Column2);
    //111
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.SetColor(HDevWindowStack.GetActive(), "green");
    }
    ho_Contours.Dispose();
    HOperatorSet.GenContourRegionXld(ho_Rectangle1, out ho_Contours, "border");
    //222
    ho_ImageReduced.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_Rectangle1, out ho_ImageReduced);
    ho_Rectangle1.Dispose();
    HOperatorSet.Threshold(ho_ImageReduced, out ho_Rectangle1, 0, 40);
    ho_RegionFillUp.Dispose();
    HOperatorSet.FillUpShape(ho_Rectangle1, out ho_RegionFillUp, "area", 1, 100);
    ho_RegionOpening.Dispose();
    HOperatorSet.OpeningCircle(ho_RegionFillUp, out ho_RegionOpening, 3.5);
    ho_ConnectedRegions.Dispose();
    HOperatorSet.Connection(ho_RegionOpening, out ho_ConnectedRegions);
    ho_SelectedRegions.Dispose();
    HOperatorSet.SelectShapeStd(ho_ConnectedRegions, out ho_SelectedRegions, "max_area", 
        70);
    ho_ReducedImage.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_SelectedRegions, out ho_ReducedImage);
    ho_Region1.Dispose();
    HOperatorSet.Threshold(ho_ReducedImage, out ho_Region1, 60, 255);
    ho_ConnectedRegions1.Dispose();
    HOperatorSet.Connection(ho_Region1, out ho_ConnectedRegions1);
    {
    HObject ExpTmpOutVar_0;
    HOperatorSet.SelectShape(ho_ConnectedRegions1, out ExpTmpOutVar_0, "area", "and", 
        1, 9999999999);
    ho_ConnectedRegions1.Dispose();
    ho_ConnectedRegions1 = ExpTmpOutVar_0;
    }
    hv_Number.Dispose();
    HOperatorSet.CountObj(ho_ConnectedRegions1, out hv_Number);
    hv_Area.Dispose();hv_Row.Dispose();hv_Column.Dispose();
    HOperatorSet.AreaCenter(ho_ConnectedRegions1, out hv_Area, out hv_Row, out hv_Column);
    HTuple end_val21 = hv_Number-1;
    HTuple step_val21 = 1;
    for (hv_Index=0; hv_Index.Continue(end_val21, step_val21); hv_Index = hv_Index.TupleAdd(step_val21))
    {
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      ho_Rectangle.Dispose();
      HOperatorSet.GenRectangle2ContourXld(out ho_Rectangle, hv_Row.TupleSelect(hv_Index), 
          hv_Column.TupleSelect(hv_Index), 10, 10, 10);
      }
    }
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.DispText(HDevWindowStack.GetActive(), "hello", "window", hv_Row, 
          hv_Column, "black", new HTuple(), new HTuple());
    }
    if (HDevWindowStack.IsOpen())
    {
      hv_WindowHandle = HDevWindowStack.GetActive();
    }
    if ((int)(new HTuple(hv_Number.TupleGreater(0))) != 0)
    {
      disp_message(hv_WindowHandle, "NG", "window", 12, 12, "red", "false");
    }
    else
    {
      disp_message(hv_WindowHandle, "OK", "window", 12, 12, "green", "false");
    }
    //121
    ho_Image.Dispose();
    ho_Rectangle1.Dispose();
    ho_Contours.Dispose();
    ho_ImageReduced.Dispose();
    ho_RegionFillUp.Dispose();
    ho_RegionOpening.Dispose();
    ho_ConnectedRegions.Dispose();
    ho_SelectedRegions.Dispose();
    ho_ReducedImage.Dispose();
    ho_Region1.Dispose();
    ho_ConnectedRegions1.Dispose();
    ho_Rectangle.Dispose();

    hv_WindowHandle1.Dispose();
    hv_Row1.Dispose();
    hv_Column1.Dispose();
    hv_Row2.Dispose();
    hv_Column2.Dispose();
    hv_Number.Dispose();
    hv_Area.Dispose();
    hv_Row.Dispose();
    hv_Column.Dispose();
    hv_Index.Dispose();
    hv_WindowHandle.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)

#endif

